// app-react/src/components/Modal.tsx
import { useRef, useEffect, type FC } from 'react';

interface ModalProps {
    message: string;
    onConfirm: () => void;
    onCancel: () => void;
}

const Modal: FC<ModalProps> = ({ message, onConfirm, onCancel }) => {
    const dialogRef = useRef<HTMLDialogElement>(null);

    useEffect(() => {
        if (dialogRef.current) {
            dialogRef.current.showModal();
        }
    }, []);

    const handleConfirm = () => {
        onConfirm();
        if (dialogRef.current) dialogRef.current.close();
    };

    const handleCancel = () => {
        onCancel();
        if (dialogRef.current) dialogRef.current.close();
    };

    return (
        <dialog ref={dialogRef} className="modal">
            <p>{message}</p>
            <div className={'modal-footer'}>
                <button onClick={handleConfirm}>Да</button>
                <button onClick={handleCancel}>Нет</button>
            </div>
        </dialog>
    );
};

export default Modal;

// app-solid/src/components/Modal.tsx
import { onMount } from 'solid-js';

interface ModalProps {
    message: string;
    onConfirm: () => void;
    onCancel: () => void;
}

const Modal = (props: ModalProps) => {
    let dialogRef: HTMLDialogElement | null;

    onMount(() => {
        if (dialogRef) {
            dialogRef.showModal();
        }
    });

    const handleConfirm = () => {
        props.onConfirm();
        if (dialogRef) dialogRef.close();
    };

    const handleCancel = () => {
        props.onCancel();
        if (dialogRef) dialogRef.close();
    };

    return (
        <dialog ref={(el) => dialogRef = el} class="modal">
            <p>{props.message}</p>
            <button onClick={handleConfirm}>Да</button>
            <button onClick={handleCancel}>Нет</button>
        </dialog>
    );
};

export default Modal;
