// app-react/src/App.tsx
import { useState } from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import TaskList from './components/TaskList';
import CreateTask from './components/CreateTask';
import TaskDetail from './components/TaskDetail';
import { TodoProvider } from './context/TodoContext';
import './App.css'

function App() {
    const [activeTab, setActiveTab] = useState<'list' | 'create'>('list');

    return (
        <main>
            <TodoProvider>
                <Router>
                        <Routes>
                            <Route path="/" element={
                                <>
                                    <div className="tabs">
                                        <button onClick={() => setActiveTab('list')} className={activeTab === 'list' ? 'active' : ''}>Список задач</button>
                                        <button onClick={() => setActiveTab('create')} className={activeTab === 'create' ? 'active' : ''}>Создать задачу</button>
                                    </div>
                                    {activeTab === 'list' ? <TaskList /> : <CreateTask />}
                                </>
                            } />
                            <Route path="/task/:id" element={<TaskDetail />} />
                        </Routes>
                </Router>
            </TodoProvider>
        </main>
    );
}

export default App;

// app-solid/src/App.tsx
import { createSignal, type JSX } from 'solid-js';
import { Dynamic } from "solid-js/web";
import { Router, Route, type RouteSectionProps } from '@solidjs/router';
import TaskList from './components/TaskList';
import CreateTask from './components/CreateTask';
import TaskDetail from './components/TaskDetail';
import { TodoProvider } from './context/TodoContext';
import './App.css'



function AppLayout(props: RouteSectionProps) {
    return (
        <main>
            <TodoProvider>
                    {props.children}
            </TodoProvider>
        </main>
    );
}

const App = () => {
    const [activeTab, setActiveTab] = createSignal<'list' | 'create'>('list');

    const tabs: Record<'list' | 'create', () => JSX.Element> = {
        list: TaskList,
        create: CreateTask
    };

    return (
        <Router root={AppLayout}>
            <Route path="/" component={() => (
                <>
                    <div class="tabs">
                        <button
                            onClick={() => setActiveTab('list')}
                            classList={{'active': activeTab() === 'list'}}
                        >
                            Список задач
                        </button>

                        <button
                            onClick={() => setActiveTab('create')}
                            classList={{'active': activeTab() === 'create'}}
                        >
                            Создать задачу
                        </button>
                    </div>
                    <div class="tab-content">
                        <Dynamic component={tabs[activeTab()]}/>
                    </div>
                </>
            )}/>
            <Route path="/task/:id" component={TaskDetail}/>
        </Router>
    );
}

export default App;
